title: "Teachu"
remote_theme: pmarsceill/just-the-docs
search_enabled: true
aux_links:
  "GitHub":
    - "//github.com/sbuljat"
  "Twitter":
    - "//twitter.com/sbuljat"

footer_content: "Copyright &copy; 2021 Stjepan Buljat. Distributed by an <a href=\"https://github.com/sbuljat/sbuljat.github.io/tree/master/LICENSE\">MIT license.</a>"

